core/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, lista_estados, estado_novo, estado_search, estado_update, estado_delete
from .views import lista_cidades, cidade_novo, cidade_search, cidade_update, cidade_delete
from .views import lista_paises, pais_novo, pais_search, pais_update, pais_delete
from .views import lista_origens, origem_novo, origem_update, origem_delete
from .views import lista_destinos, destino_novo, destino_delete, destino_update

urlpatterns = [

#url home, chama view home, cujo nome é 'home'
    path('home', home, name='home'),

#ESTADOS
    path('lista_estados', lista_estados, name='lista_estados'),
    path('estado_novo', estado_novo, name='estado_novo'),
    path('estado_update/<int:id>', estado_update, name='estado_update'),
    path('estado_delete/<int:id>', estado_delete, name='estado_delete'),
    path('estado_search', estado_search, name='estado_search'),



#CIDADES
    path('lista_cidades', lista_cidades, name='lista_cidades'),
    path('cidade_novo', cidade_novo, name='cidade_novo'),
    path('cidade_update/<int:id>', cidade_update, name='cidade_update'),
    path('cidade_delete/<int:id>', cidade_delete, name='cidade_delete'),
    path('cidade_search', cidade_search, name='cidade_search'),



#PAISES
    path('lista_paises', lista_paises, name='lista_paises'),
    path('pais_novo', pais_novo, name='pais_novo'),
    path('pais_update/<int:id>', pais_update, name='pais_update'),
    path('pais_delete/<int:id>', pais_delete, name='pais_delete'),
    path('pais_search', pais_search, name='pais_search'),


#ORIGEM
    path('lista_origens', lista_origens, name='lista_origens'),
    path('origem_novo', origem_novo, name='origem_novo'),
    path('origem_update/<int:id>', origem_update, name='origem_update'),
    path('origem_delete/<int:id>', origem_delete, name='origem_delete'),

#DESTINOS
    path('lista_destinos', lista_destinos, name='lista_destinos'),
    path('destino_novo', destino_novo, name='destino_novo'),
    path('destino_update/<int:id>', destino_update, name='destino_update'),
    path('destino_delete/<int:id>', destino_delete, name='destino_delete'),

]

siga_transportes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/models.py
from django.db import models
from django.db.models import CharField


class Estado(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'estado'

class Cidade(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'cidade'


class Pais(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'pais'

class Funcao(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)
    codigo = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'funcao'


class Origem(models.Model):
    cidade = models.ForeignKey('Cidade', null=True, on_delete=models.SET_NULL)
    estado = models.ForeignKey('Estado', null=True, on_delete=models.SET_NULL)
    pais = models.ForeignKey('Pais', null=True, on_delete=models.SET_NULL)

    class Meta:

        db_table = 'origem'

class Destino(models.Model):
    cidade = models.ForeignKey('Cidade', null=True, on_delete=models.SET_NULL)
    estado = models.ForeignKey('Estado',null=True, on_delete=models.SET_NULL)
    pais = models.ForeignKey('Pais', null=True, on_delete=models.SET_NULL)

    class Meta:

        db_table = 'destino'


class FormaPagamento(models.Model):

    tipo = models.CharField(max_length=100, blank=False, null=False)


    def __str__(self):
        return self.tipo

    class Meta:
        db_table = 'forma_pagamento'


class Cliente(models.Model):
    nome = models.CharField(max_length=80, blank=False, null=False)
    cnpj = models.CharField(db_column='CNPJ', max_length=60, blank=False, null=False)  # Field name made lowercase.
    ie = models.CharField(max_length=60, blank=False, null=False)
    email = models.CharField(max_length=100, blank=False, null=False)
    endereco = models.CharField(max_length=80, blank=False, null=False)
    telefone = models.CharField(max_length=60, blank=False, null=False)
    cidade = models.ForeignKey('Cidade', null=True, on_delete=models.SET_NULL)
    estado = models.ForeignKey('Estado', null=True, on_delete=models.SET_NULL)
    data_cadastro = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nome


    class Meta:

        db_table = 'cliente'


class Documento(models.Model):
    nome_doc = models.CharField(max_length=80, blank=False, null=False)

    def __str__(self):
        return self.nome_doc

    class Meta:

        db_table = 'documento'


class Empresa(models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)
    cnpj = models.CharField(db_column='CNPJ', max_length=80, blank=False, null=False)  # Field name made lowercase.
    ie = models.CharField(max_length=80, blank=False, null=False)
    email = models.CharField(max_length=80, blank=False, null=False)
    endereco = models.CharField(max_length=100, blank=False, null=False)
    cidade = models.ForeignKey('Cidade', null=True, on_delete=models.SET_NULL)
    estado = models.ForeignKey('Estado', null=True, on_delete=models.SET_NULL)
    fone = models.CharField(max_length=30, blank=False, null=False)
    responsavel = models.CharField(max_length=80, blank=False, null=False)
    data_inicio = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nome



    class Meta:
        db_table = 'empresa'


class Fornecedor(models.Model):
    nome = models.CharField(max_length=80, blank=False, null=False)
    cnpj = models.CharField(db_column='CNPJ', max_length=80, blank=False, null=False)  # Field name made lowercase.
    ie = models.CharField(max_length=80, blank=False, null=False)
    email = models.CharField(max_length=80, blank=False, null=False)
    endereco = models.CharField(max_length=80, blank=False, null=False)
    fone = models.CharField(max_length=30, blank=False, null=False)
    responsavel = models.CharField(max_length=80, blank=False, null=False)
    cidade = models.ForeignKey('Cidade', null=True, on_delete=models.SET_NULL)
    estado = models.ForeignKey('Estado', null=True, on_delete=models.SET_NULL)
    data_cadastro = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nome


    class Meta:
        db_table = 'fornecedor'


class Frota(models.Model):
    nome_frota = models.CharField(max_length=20, blank=False, null=False)
    empresa = models.ForeignKey('Empresa', null=True, on_delete=models.SET_NULL)
    situacoes = models.ForeignKey('Situacao', null=True, on_delete=models.SET_NULL)
    data_cadastro =models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nome_frota

    class Meta:
        db_table = 'frota'


class Exame(models.Model):
    nome = models.CharField(max_length=40, blank=False, null=False)
    cid = models.CharField(max_length=40, blank=False, null=False)
   
    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'exame'


class Funcionario(models.Model):
    nome = models.CharField(max_length=80, blank=False, null=False)
    cpf = models.CharField(db_column='CPF', max_length=50, blank=False, null=False)  # Field name made lowercase.
    pis = models.CharField(db_column='PIS', max_length=30, blank=False, null=False)  # Field name made lowercase.
    data_admissao = models.DateField(null=False, blank=True)
    data_demissao = models.DateField(null=True, blank=True)
    email = models.CharField(max_length=100, blank=False, null=False)
    endereco = models.CharField(max_length=90, blank=False, null=False)
    funcao = models.ForeignKey('Funcao', null=True, on_delete=models.SET_NULL)
    telefone = models.CharField(max_length=60, blank=False, null=False)
    cidade = models.ForeignKey('Cidade', null=True, on_delete=models.SET_NULL)
    estado = models.ForeignKey('Estado', null=True,on_delete=models.SET_NULL)
    situacoes = models.ForeignKey('situacao', null=True, on_delete=models.SET_NULL)
    obs = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.nome


    class Meta:
        db_table = 'funcionario'


class LancarBaixaVeiculo(models.Model):
    veiculo = models.ForeignKey('veiculo', null=True, on_delete=models.SET_NULL)
    data_venda = models.DateField(null=False, blank=True)
    km_final = models.IntegerField(null=False, blank=True)
    valor = models.DecimalField(max_digits=12, decimal_places=2, blank=False, null=False)
    comprador = models.CharField(max_length=60, blank=False, null=False)
    telefone_comprador = models.CharField(max_length=40, blank=False, null=False)


    class Meta:
        db_table = 'lancar_baixa_veiculo'


class LancarContabilidade(models.Model):
    data = models.DateField(null=False, blank=True)
    valor = models.DecimalField(max_digits=12, decimal_places=2, blank=False, null=False)
    historico = models.CharField(max_length=100, blank=False, null=False)
    plano_conta = models.ForeignKey('PlanoConta', null=True, on_delete=models.SET_NULL)
    documento = models.ForeignKey('Documento', null=True, on_delete=models.SET_NULL)
    empresa = models.ForeignKey('Empresa', null=True, on_delete=models.SET_NULL)
    fornecedor = models.ForeignKey('Fornecedor',null=True, on_delete=models.SET_NULL)
    veiculo = models.ForeignKey('Veiculo', null=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = 'lancar_contabilidade'


class LancarFerias(models.Model):
    funcionario = models.ForeignKey('Funcionario', null=True, on_delete=models.SET_NULL)
    data_inicio = models.DateField(null=False, blank=True)
    data_fim = models.DateField(null=False, blank=True)
    ano_referente = models.IntegerField(null=False, blank=True)
    valor = models.DecimalField(max_digits=12, decimal_places=2)


    class Meta:
        db_table = 'lancar_ferias'


class LancarFinanceiroViagem(models.Model):
    lancar_viagem = models.ForeignKey('LancarViagem', null=True, on_delete=models.SET_NULL)
    data = models.DateField(null=False, blank=True)
    valor = models.DecimalField(max_digits=12, decimal_places=2, blank=False, null=False)
    historico = models.CharField(max_length=100, blank=False, null=False)
    plano_conta = models.ForeignKey('PlanoConta', null=True, on_delete=models.SET_NULL)
    documento = models.ForeignKey('Documento', null=True, on_delete=models.SET_NULL)
    empresa = models.ForeignKey('Empresa', null=True, on_delete=models.SET_NULL)
    fornecedor = models.ForeignKey('Fornecedor', null=True,on_delete=models.SET_NULL)
  

    class Meta:
        db_table = 'lancar_financeiro_viagem'


class LancarViagem(models.Model):
    crtc = models.CharField(max_length=30, blank=False, null=False)
    data = models.DateField(null=False, blank=True)
    frota = models.ForeignKey('Frota', null=True, on_delete=models.SET_NULL)
    motorista = models.ForeignKey('Funcionario', null=True, on_delete=models.SET_NULL)
    origem = models.ForeignKey('Origem', null=True, on_delete=models.SET_NULL)
    destino = models.ForeignKey('Destino', null=True, on_delete=models.SET_NULL)
    kminicial = models.IntegerField(db_column='kmInicial')  # Field name made lowercase.
    litragem = models.FloatField(null=False, blank=True)
    qtdeveiculos = models.IntegerField(null=False, blank=True)
    fk_empresa = models.ForeignKey('Empresa', null=True, on_delete=models.SET_NULL)
    obs = models.CharField(max_length=100, blank=False, null=False)
    status = models.CharField(max_length=30, blank=False, null=False)

    def __str__(self):
        return self.crtc


    class Meta:
        db_table = 'lancar_viagem'


class PlanoConta(models.Model):
    conta = models.IntegerField(null=False, blank=True)
    tipo = models.CharField(max_length=20, blank=False, null=False)

core/forms.py
from django.forms import ModelForm
from .models import Origem, Destino, Empresa, Fornecedor, Cliente, Documento, Frota, Funcionario, PlanoConta
from .models import Situacao, AcertoViagem, TipoVeiculo, Veiculo, LancarViagem, LancarFinanceiroViagem
from .models import LancarFerias, LancarContabilidade, LancarBaixaVeiculo, Estado, Cidade, Pais


class EstadoForm(ModelForm):
    class Meta:
        model = Estado
        fields = '__all__'

class CidadeForm(ModelForm):
    class Meta:
        model = Cidade
        fields = '__all__'


class PaisForm(ModelForm):
    class Meta:
        model = Pais
        fields = '__all__'

class OrigemForm(ModelForm):
    class Meta:
        model = Origem
        fields = '__all__'

class DestinoForm(ModelForm):
    class Meta:
        model = Destino
        fields = '__all__'

class EmpresaForm(ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'

class FornecedorForm(ModelForm):
    class Meta:
        model = Fornecedor
        fields = '__all__'

class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

class DocumentoForm(ModelForm):
    class Meta:
        model = Documento
        fields = '__all__'

class FrotaForm(ModelForm):
    class Meta:
        model = Frota
        fields = '__all__'

class FuncionarioForm(ModelForm):
    class Meta:
        model = Funcionario
        fields = '__all__'

class PlanoContasForm(ModelForm):
    class Meta:
        model = PlanoConta
        fields = '__all__'


class SituacaoForm(ModelForm):
    class Meta:
        model = Situacao
        fields = '__all__'

class AcertoViagemForm(ModelForm):
    class Meta:
        model = AcertoViagem
        fields = '__all__'

class TipoVeiculoForm(ModelForm):
    class Meta:
        model = TipoVeiculo
        fields = '__all__'

class VeiculoForm(ModelForm):
    class Meta:
        model = Veiculo
        fields = '__all__'

class lancarViagemForm(ModelForm):
    class Meta:
        model = LancarViagem
        fields = '__all__'

class LancarFinanceiroViagemForm(ModelForm):
    class Meta:
        model = LancarFinanceiroViagem
        fields = '__all__'

class LancarFeriasForm(ModelForm):
    class Meta:
        model = LancarFerias
        fields = '__all__'

class LancarContabilidadeForm(ModelForm):
    class Meta:
        model = LancarContabilidade
        fields = '__all__'

class LancarBaixaVeiculoForm(ModelForm):
    class Meta:
        model = LancarBaixaVeiculo
        fields = '__all__'

core/templates/core/cidade_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form name="form2" id="form2" class="form-horizontal" method="post" action="{% url 'cidade_delete' cidade.id %}">
  {% csrf_token %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="cancelar" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Confirmação de exlusão</h4>
            </div>
            <div class="modal-body">
               
    Você tem certeza que deseja excluir o registro:{{ cidade.nome }}<b></b>?
             
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-danger">Confirmar</button>
           
          </div>
        </div>
      </div>
    </div>

</form>



{% endblock%}

core/templates/core/cidade_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">CIDADES</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="40" required id="id_nome" oninput="handleInput(event)">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus"
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>
        </div>
    </div>

    <div class="d-grid gap-2 d-md-block">
    <a href="{% url 'lista_cidades' %}"
    <Button  type= "button" class = "btn btn-warning"  style="float:right; margin-top:-66px;">
        <span class = "glyphicon glyphicon-arrow-left"
        style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Voltar</span>
    </Button>
    </a>
    </div>


    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/destino_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo" xmlns="http://www.w3.org/1999/html">DESTINO</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form3">

        <div class="form-group">
            <label class="control-label col-sm-3" for="cidade_id">Cidade:</label>
            <div class="col-sm-8">
                <select name="cidade_id" required id="cidade_id" style="width:75%; height:30px; border:#CCC solid 1px;">
                <option value="" selected >Selecione</option>
                {% for cidade in cidades %}
                    <option value="{{ cidade.id }}" >{{ cidade.nome }}</option>
                {% endfor%}
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="estado_id">Estado:</label>
            <div class="col-sm-8">
                <select name="estado_id" required id="estado_id" style="width:75%; height:30px; border:#CCC solid 1px;">
                <option value="" selected >Selecione</option>
                {% for estado in estados %}
                    <option value="{{ estado.id }}" >{{ estado.nome }}</option>
                {% endfor%}
                </select>

            </div>
        </div>

      <div class="form-group">
            <label class="control-label col-sm-3" for="pais_id">País:</label>
            <div class="col-sm-8">
                <select name="pais_id" required id="pais_id" style="width:75%; height:30px; border:#CCC solid 1px;">
                <option value="" selected >Selecione</option>
                {% for pais in paises %}
                    <option value="{{ pais.id }}" >{{ pais.nome }}</option>
                {% endfor%}
                </select>
            </div>
      </div>

  </div>
          </br>
    </br>
         </br>

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg" >
                <span class = "glyphicon glyphicon-plus"
                style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>
        </div>
    </div>

          <div class="d-grid gap-2 d-md-block">
    <a href="{% url 'lista_destinos' %}"
    <Button  type= "button" class = "btn btn-warning"  style="float:right; margin-top:-66px;">
        <span class = "glyphicon glyphicon-arrow-left"
        style="margin-left: 10px; margin-right: 10px; font-size: 18px; padding-bottom:15px;"> Voltar</span>
    </Button>
    </a>
    </div>

    </br>
          </br>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/estado_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form name="form2" id="form2" class="form-horizontal" method="post" action="{% url 'estado_delete' estado.id %}">
  {% csrf_token %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
      
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="cancelar" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Confirmação de exlusão</h4>
            </div>
            <div class="modal-body">
               
    Você tem certeza que deseja excluir a localidade:{{ localidade.cidade }}<b></b>?
             
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-danger">Confirmar</button>
           
          </div>
        </div>
      </div>
    </div>

</form>



{% endblock%}

core/templates/core/estado_update.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">ESTADOS - ATUALIZAÇÃO</div>

<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'estado_update' estado.id %}">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-16">
                <input type="text" name="nome" maxlength="2" required id="id_nome" oninput="handleInput(event)" value="{{ estado.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="container">
            <div class="row">
              <div class="col">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-edit" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Alterar</span>
            </Button>                
        </div>
        <div>

 </form>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Atenção! Confirma Exclusão?</h4>
        </div>
        <div class="modal-body">
          <p>O registro {{ estado.nome }} será excluído.</p>
        </div>
        <div class="modal-footer">
     <form name="form2" id="form2" class="form-horizontal" method="post" action="{% url 'estado_delete' estado.id %}">
                {% csrf_token %}
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Confirma</button>
        </div>
      </div>
    </div>
  </div>
</div>

</form>



<div class="d-grid gap-2 d-md-block"> 
    <a href=""
    <Button  type= "submit" class = "btn btn-danger btn-lg" data-toggle="modal" data-target="#myModal" style="float:right; margin-top:-66px;">
        <span class = "glyphicon glyphicon-trash"
        style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Excluir</span>
    </Button>       
    </a>

</div>



    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}




{% endblock %}

core/templates/core/pais_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">PAISES</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="40" required id="id_nome" oninput="handleInput(event)">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus"
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>
        </div>
    </div>

    <div class="d-grid gap-2 d-md-block">
    <a href="{% url 'lista_paises' %}"
    <Button  type= "button" class = "btn btn-warning"  style="float:right; margin-top:-66px;">
        <span class = "glyphicon glyphicon-arrow-left"
        style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Voltar</span>
    </Button>
    </a>
    </div>


    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/pais_update.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">PAISES - ATUALIZAÇÃO</div>

<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'pais_update' pais.id %}">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-16">
                <input type="text" name="nome" maxlength="40" required id="id_nome"  oninput="handleInput(event)" value="{{ pais.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="container">
            <div class="row">
              <div class="col">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-edit" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Alterar</span>
            </Button>                
        </div>
        <div>

 </form>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Atenção! Confirma Exclusão?</h4>
        </div>
        <div class="modal-body">
          <p>O registro {{ pais.nome }} será excluído.</p>
        </div>
        <div class="modal-footer">
     <form name="form2" id="form2" class="form-horizontal" method="post" action="{% url 'pais_delete' pais.id %}">
                {% csrf_token %}
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Confirma</button>
        </div>
      </div>
    </div>
  </div>
</div>

</form>



<div class="d-grid gap-2 d-md-block"> 
    <a href=""
    <Button  type= "submit" class = "btn btn-danger btn-lg" data-toggle="modal" data-target="#myModal" style="float:right; margin-top:-66px;">
        <span class = "glyphicon glyphicon-trash"
        style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Excluir</span>
    </Button>       
    </a>

</div>



    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}


{% endblock %}